# Generated by Django 5.1 on 2024-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custId", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custId", models.IntegerField(unique=True)),
                ("trans_type", models.TextField(max_length=10)),
                ("trans_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customers",
            name="custId",
            field=models.IntegerField(unique=True),
        ),
    ]
