# Generated by Django 5.1 on 2024-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_account_amount_transaction_trans_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="custId",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
