# Generated by Django 5.1 on 2024-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.TextField(max_length=50, null=True),
        ),
    ]
