# Generated by Django 5.1 on 2024-09-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_customer_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="transaction",
        ),
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.TextField(max_length=50, null=True),
        ),
    ]
