# Generated by Django 5.1 on 2024-09-06 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_delete_transaction_account_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="created",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="custId",
        ),
    ]
