# Generated by Django 5.1 on 2024-09-06 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_remove_customer_created_remove_customer_custid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="password",
        ),
    ]
