# Generated by Django 5.1 on 2024-09-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_remove_customer_name_remove_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.TextField(max_length=50, null=True),
        ),
    ]
