# Generated by Django 5.1 on 2024-09-06 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_customer_name_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="custId",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
