# Generated by Django 5.1 on 2024-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_customer_created_customer_custid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custId", models.IntegerField(unique=True)),
                ("trans_type", models.TextField(max_length=50, null=True)),
                ("trans_amount", models.IntegerField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
