# Generated by Django 5.1 on 2024-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="custId",
            field=models.IntegerField(),
        ),
    ]
